### PR TITLE
 Update validation.php for laravel 10 (2024) 

### PR DESCRIPTION
**Pull request by joukhar**
fix translations and added laravel 10 new rules

### CODE REVIEW

**Review by BSN4 — APPROVED** [review]
LGTM

**Comment by joukhar** [comment]
it has been 5 months omg !

**Comment by BSN4** [comment]
> it has been 5 months omg !

sorry, we are small team basically two devs working on 12 repos for "free" ..  I hope you understand our position... anyway thanks for your contribution

**Comment by joukhar** [comment]
@BSN4 
I didn't mean anything wrong, I really respect your efforts :heart: 
and i will keep supporting the project

**Pull request merged**
